### ISSUE TITLE
[功能请求]监听控制中心消息并利用bot原文发送

### ISSUE THREAD

**Issue by LsrlYrsc** [quqiOnfree/qqbot#3]
如题
例:控制中心弹出一则消息，qqbot成功收到并获取信息发送到群聊(启用/关闭通知开关)
建议可以分辨单个软件通知，然后针对性发送控制中心消息
可以选择定时监听发送 或者 一监听到弹出消息就发送

**Comment by quqiOnfree** [comment]
我觉得这个想法非常好，但是我想请假一下
1. 控制中心是什么
2. 如何监听

**Comment by LsrlYrsc** [comment]
控制中心是指Windows8(可能不准确)开始的新功能
在Windows10的右下角有一个类似于_信息_的图标，点开它就可以查看通知信息(比如Windows Update)
在一开始的时候，他会向桌面弹出一个消息，往右滑或者静候会收回到控制面板

我也不知道如何能实现监听这个消息的功能
主要意思是bot监听到控制中心有新消息出现，然后获取消息信息进行广播到QQ群/私聊

**Comment by quqiOnfree** [comment]
很抱歉，我查阅了网上的实现方法，目前没有办法去检索“Toast”通知
![image](https://github.com/quqiOnfree/qqbot/assets/85858209/eb2c3bf1-ec0e-40d2-ae49-c7e74eebd05e)
